### ISSUE TITLE
dx 9 + 10 + 11

### ISSUE THREAD

**Issue by ghost** [rdbo/DX11-BaseHook#2]
is there a way to hook to a game that uses directx 9,~10~ and 11 at same time
with directx 11 hook it crashes
but with directx 9 hook it does not show imgui

**Comment by rdbo** [comment]
What do you mean "a game that uses DX9, DX10 and DX11"? You mean the game allow you to change between the graphical API? And what game is it?

**Comment by ghost** [comment]
> 
> 
> What do you mean "a game that uses DX9, DX10 and DX11"? You mean the game allow you to change between the graphical API? And what game is it?

it is minecraft education edition, and it also does not allow to change the graphical api, i think it uses the latest supported dx

upd: only dx 9 and 11
![изображение](https://user-images.githubusercontent.com/70862504/107878141-b3e8af80-6ee1-11eb-89bf-f6a305738e35.png)

**Comment by rdbo** [comment]
Alright, the problem should be fixed. The issue was the call convention for x86_32. Try compiling the code and injecting again.

**Comment by ghost** [comment]
> Alright, the problem should be fixed. The issue was the call convention for x86_32. Try compiling the code and injecting again.

thank you so much, it works now
![Minecraft.Windows_mex8wuuLAu.png](https://user-images.githubusercontent.com/70862504/107880184-45f6b500-6eee-11eb-83b8-2500aff12da9.png)
